# Generated by Django 5.2.9 on 2025-12-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=10, verbose_name='Número de Ticket')),
                ('status', models.CharField(choices=[('WAITING', 'En espera'), ('CALLED', 'Llamado'), ('ATTENDED', 'Atendido'), ('CANCELED', 'Cancelado')], default='WAITING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Hora de creación')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de llamado')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de atención')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
