# Generated by Django 5.2.9 on 2025-12-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='duration',
            field=models.IntegerField(default=5, help_text='Tiempo de visualización para imágenes', verbose_name='Duración (segundos)'),
        ),
        migrations.AddField(
            model_name='slider',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Imagen'), ('VIDEO', 'Video')], default='IMAGE', max_length=10, verbose_name='Tipo de medio'),
        ),
        migrations.AddField(
            model_name='slider',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='sliders/videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/', verbose_name='Imagen'),
        ),
    ]
