# Generated by Django 5.2.10 on 2026-03-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_slider_duration_slider_media_type_slider_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='service_type',
            field=models.CharField(choices=[('RESULTS', 'Retirar Resultados'), ('ANALYSIS', 'Realizar Análisis'), ('BUDGET', 'Solicitar Presupuesto')], default='ANALYSIS', max_length=20, verbose_name='Servicio / Prioridad'),
        ),
    ]
