# Generated by Django 5.2.13 on 2026-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ticket_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='sliders/', verbose_name='Imagen'),
        ),
    ]
