# Generated by Django 5.2.15 on 2026-06-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_slider_image_to_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='has_sound',
            field=models.BooleanField(default=True, help_text='Indica si el video se reproducirá con sonido', verbose_name='Con sonido'),
        ),
    ]
