# Generated by Django 5.2.15 on 2026-07-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_slider_has_sound'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la voz')),
                ('onnx_file', models.FileField(upload_to='voices/', verbose_name='Archivo .onnx')),
                ('json_file', models.FileField(upload_to='voices/', verbose_name='Archivo .json')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Voz',
                'verbose_name_plural': 'Voces',
                'ordering': ['-created_at'],
            },
        ),
    ]
